# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-22 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabbook',
            name='being_edited_by',
            field=models.IntegerField(default=None),
        ),
    ]
