# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-23 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='books.Book'),
        ),
    ]
