# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-22 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_collabbook_being_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CollabBook',
        ),
    ]
