# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-23 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='authors',
        ),
    ]
