# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_library_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='test',
            field=models.TextField(default=':FUCL'),
        ),
    ]
