# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-23 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_library_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='finished',
            new_name='is_finished',
        ),
        migrations.RemoveField(
            model_name='library',
            name='test',
        ),
    ]
